disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Sound Portfolio"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  #logo = "img/image.jpg"
 #secondaryLogo = "img/image.jpg"
   description = "an exploration of immersive audio, sound design, and interactive media for games, film, and new storytelling forms. Created by Mike Ballard, this portfolio showcases experimental projects, audio environments, and interactive soundscapes."
   copyright = "Copyright &copy; { year } "

 [params.author]
   name = "Mike Ballard"
   email = "youremail@example.com"
   #image = "img/logo.jpg"
   imageQuality = 96
    headline = "Sound Designer navigating the hauntological and the eerie."
    bio = "I'm a musician, sound designer, and creative technologist exploring the boundaries between sound, space, and memory. With the Horses of the Gods, I create eerie, folk-infused atmospheres, blending acoustic instruments with field recordings and digital synthesis. In my sound design work, I aim to capture the liminal and the hauntological through immersive audio experiences that evoke the forgotten, the in-between, and the strange. As a maker, I am known as Shedtronic, and my work spans creative technology, sound exploration, and experimental design. Below, you'll find links to my projects as a sound designer, maker and creative technologist, showcasing my dedication to merging the physical and digital in innovative ways."

   links = [
      { soundcloud = "https://soundcloud.com/shedtronic" },
      { youtube = "https://www.youtube.com/@shedtronic" },
#     { email = "mailto:hello@your_domain.com" },
      { link = "https://linktr.ee/shedtronic" },
#     { amazon = "https://www.amazon.com/hz/wishlist/ls/wishlist-id" },
#     { apple = "https://www.apple.com" },
#     { blogger = "https://username.blogspot.com/" },
      { bluesky = "https://bsky.app/profile/shedtronic.bsky.social" },
      { mastodon = "https://mastodon.world/@shedtronic" },
#     { codepen = "https://codepen.io/username" },
#     { dev = "https://dev.to/username" },
#     { discord = "https://discord.gg/invitecode" },
#     { dribbble = "https://dribbble.com/username" },
#     { facebook = "https://facebook.com/username" },
#     { flickr = "https://www.flickr.com/photos/username/" },
#     { foursquare = "https://foursquare.com/username" },
#     { gitlab = "https://gitlab.com/username" },
#     { google = "https://www.google.com/" },
#     { hashnode = "https://username.hashnode.dev" },
#     { instagram = "https://instagram.com/shedtronic" },
#     { itch-io = "https://username.itch.io" },
#     { keybase = "https://keybase.io/username" },
#     { kickstarter = "https://www.kickstarter.com/profile/username" },
#     { lastfm = "https://lastfm.com/user/username" },
      { linkedin = "https://linkedin.com/in/shedtronic" },
      { github = "https://github.com/shedtronic" },
      { link = "https://pushingtheenvelopegenerator.substack.com/" },
      { medium = "https://medium.com/@shedtronic" },
#     { microsoft = "https://www.microsoft.com/" },
#     { orcid = "https://orcid.org/userid" },
#     { patreon = "https://www.patreon.com/username" },
#     { pinterest = "https://pinterest.com/username" },
#     { reddit = "https://reddit.com/user/username" },
#     { researchgate = "https://www.researchgate.net/profile/username" },
#     { slack = "https://workspace.url/team/userid" },
#     { snapchat = "https://snapchat.com/add/username" },
      
     { spotify = "https://open.spotify.com/artist/3hd3jY357TOCmwGrpDAUeC" },
#     { stack-overflow = "https://stackoverflow.com/users/userid/username" },
#     { steam = "https://steamcommunity.com/profiles/userid" },
#     { telegram = "https://t.me/username" },
#     { threads = "https://www.threads.net/@shedtronic" },
      { tiktok = "https://tiktok.com/@shedtronic" },
#     { tumblr = "https://username.tumblr.com" },
#     { twitch = "https://twitch.tv/username" },
#     { twitter = "https://twitter.com/username" },
#     { x-twitter = "https://twitter.com/username" },
#     { whatsapp = "https://wa.me/phone-number" },
#     { ko-fi = "https://ko-fi.com/username" },
#     { codeberg = "https://codeberg.org/username"},
  ]
